### ISSUE TITLE
Can't create tickets

### ISSUE THREAD

**Issue by jasonm** [hybridgroup/taskmapper-pivotal#1]
Hello,

I can't seem to create a ticket using tickletmaster-pivotal, and don't get any feedback as to why.  I'm trying to follow along with the example in the ticketmaster README:

https://gist.github.com/72d8aaf66e2ae49cebc0

Any ideas?  I wonder if there are validation errors coming back from PT that aren't displayed to me?  Thanks!
-Jason

**Comment by kiafaldorius** [comment]
Ah, it should be :title instead of :summary. Pivotal actually takes :name instead, however, I've updated the gem to be able to accept all three options, :title, :summary and :name.

And I have also updated the README for ticketmaster.

Released as version 0.3.9.

Thanks!

**Comment by deadprogram** [comment]
Looks like this was fixed. Closing...
